{{- $sparqlSecretName := include "data-cube-curation.sparql.secretName" . -}}
{{- $gitlabSecretName := include "data-cube-curation.gitlab.secretName" . -}}
{{- $s3SecretName := include "data-cube-curation.s3.secretName" . -}}

{{- if (not .Values.dataCubeCuration.sparql.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $sparqlSecretName }}
  labels:
    {{- include "data-cube-curation.labels" . | nindent 4 }}
data:
{{- if .Values.dataCubeCuration.sparql.username }}
  username: {{ .Values.dataCubeCuration.sparql.username | print | b64enc }}
{{- end -}}

{{- if .Values.dataCubeCuration.sparql.password }}
  password: {{ .Values.dataCubeCuration.sparql.password | print | b64enc }}
{{- end }}
  endpoint: {{ required "A valid dataCubeCuration.sparql.endpoint entry is required!" .Values.dataCubeCuration.sparql.endpoint | print | b64enc }}

{{- if .Values.dataCubeCuration.sparql.updateEndpoint }}
  updateEndpoint: {{ .Values.dataCubeCuration.sparql.updateEndpoint | print | b64enc }}
{{- end }}
  readModelEndpoint: {{ required "A valid dataCubeCuration.sparql.readModelEndpoint entry is required!" .Values.dataCubeCuration.sparql.readModelEndpoint | print | b64enc }}

{{- if .Values.dataCubeCuration.sparql.readModelUpdateEndpoint }}
  readModelUpdateEndpoint: {{ .Values.dataCubeCuration.sparql.readModelUpdateEndpoint | print | b64enc }}
{{- end }}

  graphStoreEndpoint: {{ required "A valid dataCubeCuration.sparql.graphStoreEndpoint entry is required!" .Values.dataCubeCuration.sparql.graphStoreEndpoint | print | b64enc }}
{{- if .Values.dataCubeCuration.sparql.graphStoreUsername }}
  graphStoreUsername: {{ .Values.dataCubeCuration.sparql.graphStoreUsername | print | b64enc }}
{{- end -}}

{{- if .Values.dataCubeCuration.sparql.graphStorePassword }}
  graphStorePassword: {{ .Values.dataCubeCuration.sparql.graphStorePassword | print | b64enc }}
{{- end }}
---
{{ end -}}

{{- if (not .Values.dataCubeCuration.s3.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $s3SecretName }}
  labels:
    {{- include "data-cube-curation.labels" . | nindent 4 }}
data:
  accessKey: {{ required "A valid dataCubeCuration.s3.accessKey entry is required!" .Values.dataCubeCuration.s3.accessKey | print | b64enc }}
  secretKey: {{ required "A valid dataCubeCuration.s3.secretKey entry is required!" .Values.dataCubeCuration.s3.secretKey | print | b64enc }}
---
{{ end -}}

{{- if (not .Values.dataCubeCuration.gitlab.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $gitlabSecretName }}
  labels:
    {{- include "data-cube-curation.labels" . | nindent 4 }}
data:
  token: {{ required "A valid dataCubeCuration.gitlab.token entry is required!" .Values.dataCubeCuration.gitlab.token | print | b64enc }}
---
{{ end -}}
