---
language: go
go:
  - "1.13"
dist: xenial

env:
  global:
    - OUT_DIR=out

install:
  - curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
  - sudo apt-get install jq

before_script:
  - git fetch origin gh-pages

if: branch = master OR type = pull_request

script: ./.ci/build.sh

deploy:
  provider: pages
  local-dir: $OUT_DIR
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
