{{- if eq .Values.haproxy.config "galera"}}
{{- $galera := .Values.haproxy.galera -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ include "haproxy.fullname" . }}-galera"
  labels:
    app.kubernetes.io/name: {{ include "haproxy.name" . }}
    helm.sh/chart: {{ include "haproxy.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  haproxy.cfg: |
    global
      log stdout local0

    resolvers mydns
      parse-resolv-conf
      accepted_payload_size 8192 # allow larger DNS payloads

    defaults
      log global

      option dontlognull
      timeout connect {{ $galera.timeout.connect }}
      timeout client {{ $galera.timeout.client }}
      timeout server {{ $galera.timeout.client }}

    {{- if .Values.metrics.enabled }}
    frontend stats
      mode http
      bind *:9000

      stats enable
      stats uri /stats
      stats refresh 3s

      option http-use-htx
      http-request use-service prometheus-exporter if { path /metrics }
    {{- end }}

    frontend galera-in
      bind *:{{ .Values.haproxy.frontendPort }}
      mode tcp
      option clitcpka
      default_backend galera-nodes

    backend galera-nodes
      mode tcp
      option srvtcpka
      balance {{ $galera.balance }}
      {{ if and $galera.check.enabled $galera.check.mysql.enabled }}option mysql-check user {{ $galera.check.mysql.user }}{{ end }}
      default-server init-addr none {{ if $galera.check.enabled }} check{{ end }} resolvers mydns
      {{- range $index, $node := .Values.haproxy.galera.nodes }}
      server node-{{ $index }} {{ $node.address }}:{{ default "3306" $node.port }}{{ if $node.backup }} backup{{ end }}
      {{- end }}
{{- end }}
