{{- if .Values.metrics.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "haproxy.fullname" . }}-metrics
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/name: {{ include "haproxy.name" . }}
    helm.sh/chart: {{ include "haproxy.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: "metrics"
    {{- if .Values.metrics.service.labels -}}
    {{- toYaml .Values.metrics.service.labels | nindent 4 }}
    {{- end -}}
  {{- if .Values.metrics.service.annotations }}
  annotations: {{- toYaml .Values.metrics.service.annotations | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.metrics.service.type }}
  {{ if and (eq .Values.metrics.service.type "LoadBalancer") .Values.metrics.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.metrics.service.loadBalancerIP }}
  {{- end }}
  ports:
    - name: metrics
      port: 9000
      targetPort: metrics
  selector:
    app.kubernetes.io/name: {{ include "haproxy.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
