{{- if and (eq .Values.haproxy.config "redisk8s") .Values.haproxy.redisk8s.check.enabled  }}
{{- if (empty .Values.haproxy.check.existingSecret.name) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "haproxy.fullname" . }}-check-auth
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/name: {{ include "haproxy.name" . }}
    helm.sh/chart: {{ include "haproxy.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  {{- if not (empty .Values.haproxy.redisk8s.check.redis.auth ) }}
  auth-credentials: {{ .Values.haproxy.redisk8s.check.redis.auth | b64enc | quote }}
  {{- end }}
{{- end }}
{{- end }}
