{{- if .Values.metrics.prometheusOperator }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "stardog.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "stardog.name" . }}
    helm.sh/chart: {{ include "stardog.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "stardog.name" . }}
  endpoints:
  - basicAuth:
      password:
        name: {{ include "stardog.fullname" . }}-user-passwords
        key: admin
      username:
        # unless there is a cleaner way of doing this, the name "admin" must be stored in a secret:
        name: {{ template "stardog.fullname" . }}-admin-username
        key: adminusername
    interval: 3s
    path: /admin/status/prometheus
    port: stardog
    scrapeTimeout: 3s
  jobLabel: app.kubernetes.io/instance
  podTargetLabels:
    - app.kubernetes.io/component
    - app.kubernetes.io/name
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "stardog.fullname" . }}-admin-username
  labels:
    app.kubernetes.io/name: {{ include "stardog.name" . }}
    helm.sh/chart: {{ include "stardog.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
stringData:
  adminusername: admin
{{- end }}
