{{- if .Values.metrics.prometheusOperator }}
{{- $ns_selector :=  printf "namespace=\"%s\"" .Release.Namespace }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ include "stardog.fullname" . }}-java-rules
  labels:
    app.kubernetes.io/name: {{ include "stardog.name" . }}
    helm.sh/chart: {{ include "stardog.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    role: alert-rules
spec:
  groups:

  - name: Memory Usage
    rules:
      - alert: JavaLowHeapMemory
        expr: dbms_memory_heap_max{ {{ $ns_selector }} } - dbms_memory_heap_used{ {{ $ns_selector }} } < 128 * 1024 * 1024
        for: 1m
        annotations:
          summary: Java Low Heap Memory
          description: Less than 128M of heap memory is available ({{ "{{" }} $value {{ "}}" }}).
        labels:
          env: {{ .Release.Name }}
          app: stardog
          severity: warning
{{- end }}
