{{- if .Values.rbac.create }}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  labels:
{{ include "k8up.labels" . | indent 4 }}
  name: {{ include "k8up.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "k8up.fullname" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  name: {{ include "k8up.fullname" . }}
  kind: ClusterRole
{{- end -}}
