{{- if .Values.rbac.create }}
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ include "k8up.fullname" . }}
  labels:
{{ include "k8up.labels" . | indent 4 }}
rules:
- apiGroups:
    - apiextensions.k8s.io
  resources:
    - customresourcedefinitions
  verbs:
    - get
    - watch
    - list
    - create
    - edit
    - patch
- apiGroups:
    - backup.appuio.ch
  resources:
    - '*'
  verbs:
    - '*'
- apiGroups:
    - ''
  resources:
    - pods
    - pods/exec
    - persistentvolumeclaims
    - events
    - serviceaccounts
  verbs:
    - '*'
- apiGroups:
    - batch
  resources:
    - jobs
  verbs:
    - '*'
- apiGroups:
    - rbac.authorization.k8s.io
  resources:
    - rolebindings
    - roles
  verbs:
    - '*'
- apiGroups:
    - apps
  resources:
    - deployments
    - deployments/scale
  verbs:
    - create
    - delete
    - watch
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "k8up.fullname" . }}-edit
  labels:
{{ include "k8up.labels" . | indent 4 }}
    # Add these permissions to the "admin" and "edit" default roles.
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
rules:
  - apiGroups:
      - backup.appuio.ch
    resources:
      - "*"
    verbs:
      - "*"
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "k8up.fullname" . }}-view
  labels:
{{ include "k8up.labels" . | indent 4 }}
    # Add these permissions to the "view" default role.
    rbac.authorization.k8s.io/aggregate-to-view: "true"
rules:
  - apiGroups:
      - backup.appuio.ch
    resources:
      - "*"
    verbs:
      - get
      - list
      - watch
{{- end -}}
