apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "k8up.fullname" . }}
  labels:
{{ include "k8up.labels" . | indent 4 }}
spec:
  # Running more than 1 replica is not supported, thus not configurable.
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "k8up.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "k8up.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: k8up-operator
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          {{- with .Values.k8up.backupImage }}
            - name: BACKUP_IMAGE
              value: "{{ .repository}}:{{ .tag }}"
          {{- end }}
          {{- if .Values.k8up.envVars }}
            {{- toYaml .Values.k8up.envVars | nindent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: 8080
          livenessProbe:
            httpGet:
              path: /metrics
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      serviceAccountName: {{ template "k8up.serviceAccountName" . }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
