{{- if and .Values.metrics.enabled .Values.metrics.service.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "k8up.fullname" . }}-metrics
  labels:
{{ include "k8up.labels" . | indent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: metrics
      port: {{ .Values.metrics.service.port }}
      targetPort: http
  selector:
    {{- include "k8up.selectorLabels" . | nindent 4 }}
{{- end -}}
