{{- if .Values.config.clusterAccess.enabled }}
# enabled by default by can be disabled
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "stardog-userrole-operator.fullname" . }}-manager
  labels:
{{ include "stardog-userrole-operator.labels" . | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "stardog-userrole-operator.fullname" . }}-manager
subjects:
  - kind: ServiceAccount
    name: {{ template "stardog-userrole-operator.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end -}}
{{- if .Values.metrics.proxy.enabled }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "stardog-userrole-operator.fullname" . }}-proxy
  labels:
{{ include "stardog-userrole-operator.labels" . | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "stardog-userrole-operator.fullname" . }}-proxy
subjects:
  - kind: ServiceAccount
    name: {{ template "stardog-userrole-operator.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end -}}
