{{- if .Values.metrics.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "stardog-operator.fullname" . }}-metrics
  labels:
{{ include "stardog-operator.labels" . | indent 4 }}
spec:
  type: ClusterIP
  ports:
    {{- if .Values.metrics.service.enabled }}
    - name: metrics
      port: {{ .Values.metrics.service.port }}
      targetPort: metrics
    {{- end }}
    {{- if .Values.metrics.proxy.enabled }}
    - name: https
      port: {{ .Values.metrics.proxy.port }}
      targetPort: https
    {{- end }}
  selector:
{{ include "stardog-operator.selectorLabels" . | indent 4 }}
{{- end -}}