{{- $ingress := .Values.ingress -}}
{{- if $ingress.enabled -}}
{{- $fullName := include "stardog.fullname" . -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    app.kubernetes.io/name: {{ include "stardog.name" . }}
    helm.sh/chart: {{ include "stardog.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  {{- with $ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if $ingress.tls }}
  tls:
  {{- range $ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  {{- range (required "ingress.hosts is required when using ingress" $ingress.hosts) }}
    - host: {{ . | quote }}
      http:
        paths:
          - path: {{ $ingress.path }}
            backend:
              serviceName: {{ $fullName }}
              servicePort: stardog
  {{- end }}
{{- end }}
