{{- if and (not .Values.stardog.existingPullSecret) .Values.image.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "stardog.fullname" . }}-pullsecret
  labels:
    app.kubernetes.io/name: {{ include "stardog.name" . }}
    helm.sh/chart: {{ include "stardog.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "stardog.imagePullSecret" . }}
{{- end -}}
