apiVersion: v1
kind: Service
metadata:
  name: {{ include "stardog.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "stardog.name" . }}
    helm.sh/chart: {{ include "stardog.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
    - port: 5820
      targetPort: 5820
      name: stardog
  selector:
    app.kubernetes.io/name: {{ include "stardog.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
