---
image:
  repository: openshift/oauth-proxy
  tag: v1.1.0
  pullPolicy: IfNotPresent
serviceaccount:
  name: openshift-oauth-proxy
  annotations:
    
extraArgs:
- upstream: http://localhost:9090
- openshift-sar: '{"resource": "namespaces", "verb": "get"}'
- openshift-delegate-urls: '{"/": {"resource": "namespaces", "verb": "get"}}'
route:
  annotations:
    kubernetes.io/tls-acme: "true"
  tls: true
