apiVersion: v1
appVersion: 2.3.4
description: A Helm chart for HAProxy which can be customized by a config map.
name: haproxy
version: 1.3.3
maintainers:
  - name: APPUiO Team
    email: info@appuio.ch
