{{- $endpoint := .Values.trifid.sparql.endpoint -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "trifid.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ template "trifid.name" . }}
    helm.sh/chart: {{ template "trifid.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ template "trifid.name" . }}
      helm.sh/chart: {{ template "trifid.chart" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/managed-by: {{ .Release.Service }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ template "trifid.name" . }}
        helm.sh/chart: {{ template "trifid.chart" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: SPARQL_ENDPOINT_URL
            value: {{ $endpoint.url }}
          - name: SPARQL_USERNAME
            valueFrom:
              secretKeyRef:
                name: {{ if $endpoint.secretName }}{{ $endpoint.secretName }}{{ else }}{{ include "trifid.fullname" . }}{{ end }}
                key: username
          - name: SPARQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ if $endpoint.secretName }}{{ $endpoint.secretName }}{{ else }}{{ include "trifid.fullname" . }}{{ end }}
                key: password
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
