{{- $endpoint := .Values.trifid.sparql.endpoint -}}
{{- if not $endpoint.secretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "trifid.fullname" . }}
  labels:
    {{- include "trifid.labels" . | nindent 4 }}
type: Opaque
data:
  username: {{ $endpoint.username | b64enc }}
  password: {{ $endpoint.password | b64enc }}
{{- end }}
