{{- $endpoint := .Values.trifid.sparql.endpoint -}}
{{- if not $endpoint.secretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "trifid.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ template "trifid.name" . }}
    helm.sh/chart: {{ template "trifid.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  username: {{ $endpoint.username | b64enc }}
  password: {{ $endpoint.password | b64enc }}
{{- end }}
