{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "trifid.serviceAccountName" . }}
  labels:
{{ include "trifid.labels" . | nindent 4 }}
{{- end -}}
