{{- if kindIs "slice" .Values.secrets }}
{{- range .Values.secrets }}
---
apiVersion: v1
kind: Secret
type: {{ default "Opaque" .type }}
metadata:
  name: {{ .name }}
  labels:
    {{- include "secret.labels" $ | nindent 4 }}
    {{- with .labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
stringData:
  {{- toYaml .values | nindent 2 -}}
{{- end -}}
{{- end -}}
