{{- range $name, $value := .Values.secrets }}
---
{{- with $value }}
apiVersion: v1
kind: Secret
type: {{ default "Opaque" .type }}
metadata:
  name: {{ default $name .name }}
  labels:
    {{- include "secret.labels" $ | nindent 4 }}
    {{- with .labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- if .stringData }}
stringData:
  {{- toYaml .stringData | nindent 2 -}}
  {{- range $key, $template := .stringDataTemplates }}
  {{ $key }}: {{ tpl $template $ | toYaml  | indent 2 }}
  {{- end }}
{{- end }}
{{- if .data }}
data:
  {{- toYaml .data | nindent 2 }}
{{- end }}
{{- end -}}
{{- end -}}
