apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cloud-portal.fullname" . }}
  labels:
    {{- include "cloud-portal.labels" . | nindent 4 }}
data:
  config.json: |
    {{- toJson .Values.portal.config | nindent 4 }}
