---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "cloud-portal.fullname" . }}
  labels:
    {{- include "cloud-portal.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "cloud-portal.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "cloud-portal.fullname" . }}-api
  labels:
    {{- include "cloud-portal.labels" . | nindent 4 }}
spec:
  type: ExternalName
  externalName: {{ .Values.ingress.backends.api.externalName }}
  ports:
    - port: 443
      targetPort: 443
      protocol: TCP
      name: https
