---
# -- Dict with key/values. Each key is the name of the secret.
# Each value may contain an object with `.name`, `.type`, `.stringData`, `.data`, `.labels`, `.annotations`.
# If `.name` is not given, the key name is used.
# See an example in `values.yaml`.
secrets: {}
# secrets:
#   my-secret-name:
#     name: overridden-name # optional
#     stringData:
#       my-user: example
#       my-file: |
#         [section]
#         config = value
#     data:
#       my-key: some-base64-encoded-string
#     labels: # optional
#       app: database
#     annotations: # optional
#       my-annotation: a string value
