apiVersion: v1
kind: Secret
metadata:
  name: {{ include "signalilo.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "signalilo.name" . }}
    helm.sh/chart: {{ include "signalilo.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  config.yaml: {{ .Values.config | toYaml | b64enc }}
