apiVersion: v1
description: Prometheus Blackbox Exporter
name: prometheus-blackbox-exporter
version: 0.3.1
appVersion: v0.17.0
home: https://github.com/prometheus/blackbox_exporter
sources:
  - https://github.com/prometheus/blackbox_exporter
keywords:
  - prometheus
  - blackbox
  - monitoring
maintainers:
  - name: APPUiO Team
    email: info@appuio.ch
